import { InboxItem, SourceType } from './types';

export const MOCK_INBOX: InboxItem[] = [
  {
    id: 'e-1',
    source: SourceType.EMAIL,
    sender: 'ceo@company.com',
    subject: 'Urgent: Quarterly Review Meeting Prep',
    content: 'I need the slide deck for the board meeting by 2 PM today. Please prioritize this above all else. - Sarah',
    timestamp: '2023-10-27T09:05:00Z',
    read: false,
  },
  {
    id: 's-1',
    source: SourceType.SLACK,
    sender: 'Dave (DevOps)',
    subject: 'Production Alert',
    content: 'API latency is spiking on the payment gateway. Investigating now, might need your approval for a rollback.',
    timestamp: '2023-10-27T09:15:00Z',
    read: false,
  },
  {
    id: 'j-1',
    source: SourceType.JIRA,
    sender: 'Project Manager',
    subject: 'TICKET-4201',
    content: 'Update content for the landing page footer. Low priority.',
    timestamp: '2023-10-26T16:00:00Z',
    read: true,
  },
  {
    id: 'e-2',
    source: SourceType.EMAIL,
    sender: 'newsletter@techweekly.com',
    subject: 'This week in AI',
    content: 'Top stories: Gemini 2.5 released, new coding frameworks...',
    timestamp: '2023-10-27T08:00:00Z',
    read: false,
  },
  {
    id: 's-2',
    source: SourceType.SLACK,
    sender: 'Emily (Marketing)',
    subject: 'Lunch?',
    content: 'Hey! Are we still on for tacos at 12:30?',
    timestamp: '2023-10-27T10:30:00Z',
    read: false,
  },
  {
    id: 'e-3',
    source: SourceType.EMAIL,
    sender: 'client-VIP@enterprise.com',
    subject: 'Contract Renewal - Urgent Question',
    content: 'Before we sign, we have one critical blocker regarding the SLA terms. Can we hop on a call?',
    timestamp: '2023-10-27T09:45:00Z',
    read: false,
  },
  {
    id: 'j-2',
    source: SourceType.JIRA,
    sender: 'QA Team',
    subject: 'BUG-902',
    content: 'Critical Blocker: Login page crashes on Safari iOS. Needs immediate fix.',
    timestamp: '2023-10-27T08:30:00Z',
    read: false,
  },
  {
    id: 'c-1',
    source: SourceType.CALENDAR,
    sender: 'HR',
    subject: 'Open Enrollment Reminder',
    content: 'Don\'t forget to select your benefits by Friday.',
    timestamp: '2023-10-27T09:00:00Z',
    read: false,
  },
   {
    id: 's-3',
    source: SourceType.SLACK,
    sender: 'General Channel',
    subject: 'Happy Birthday!',
    content: 'Happy birthday to Mike! Cake in the breakroom.',
    timestamp: '2023-10-27T11:00:00Z',
    read: false,
  },
   {
    id: 'e-4',
    source: SourceType.EMAIL,
    sender: 'legal@company.com',
    subject: 'Compliance Training Due',
    content: 'Please complete your annual security training by end of day tomorrow.',
    timestamp: '2023-10-27T07:00:00Z',
    read: false,
  }
];
